In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

In [2]:
df = pd.read_csv("Social_Network_Ads.csv")

df.columns = df.columns.str.strip()

print("Dataset loaded successfully")
df.head()

Dataset loaded successfully

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [3]:
print("Dataset Information:")
df.info()

print("\nShape of Dataset:")
print(df.shape)

print("\nColumn Names:")
print(df.columns)

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   User ID          400 non-null    int64
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64
 3   EstimatedSalary  400 non-null    int64
 4   Purchased        400 non-null    int64
dtypes: int64(4), object(1)
memory usage: 15.8+ KB

Shape of Dataset:
(400, 5)

Column Names:
Index(['User ID', 'Gender', 'Age', 'EstimatedSalary', 'Purchased'], dtype='object')

In [4]:
print("Missing values in each column:")
print(df.isnull().sum())

Missing values in each column:
User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [5]:
numeric_columns = df.select_dtypes(include=[np.number]).columns

for col in numeric_columns:
    df[col] = df[col].fillna(df[col].median())

categorical_columns = df.select_dtypes(include=["object"]).columns

for col in categorical_columns:
    df[col] = df[col].fillna(df[col].mode()[0])

print("Missing values after filling:")
print(df.isnull().sum())

Missing values after filling:
User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [6]:
if "Gender" in df.columns:
    label_encoder = LabelEncoder()
    df["Gender"] = label_encoder.fit_transform(df["Gender"])

print("Dataset after encoding categorical column:")
df.head()

Dataset after encoding categorical column:

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510       1   19            19000          0
1  15810944       1   35            20000          0
2  15668575       0   26            43000          0
3  15603246       0   27            57000          0
4  15804002       1   19            76000          0

In [7]:
if "User ID" in df.columns:
    df = df.drop("User ID", axis=1)

print("Dataset after removing User ID column:")
df.head()

Dataset after removing User ID column:

   Gender  Age  EstimatedSalary  Purchased
0       1   19            19000          0
1       1   35            20000          0
2       0   26            43000          0
3       0   27            57000          0
4       1   19            76000          0

In [8]:
target_column = "Purchased"

print("Target column:", target_column)

Target column: Purchased

In [9]:
X = df.drop(target_column, axis=1)

y = df[target_column]

print("Input Features:")
print(X.head())

print("\nTarget Variable:")
print(y.head())

Input Features:
   Gender  Age  EstimatedSalary
0       1   19            19000
1       1   35            20000
2       0   26            43000
3       0   27            57000
4       1   19            76000

Target Variable:
0    0
1    0
2    0
3    0
4    0
Name: Purchased, dtype: int64

In [10]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.25,
    random_state=42
)

print("Training data size:", X_train.shape)
print("Testing data size:", X_test.shape)

Training data size: (300, 3)
Testing data size: (100, 3)

In [11]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

print("Feature scaling completed")

Feature scaling completed

In [12]:
model = LogisticRegression()

In [13]:
model.fit(X_train, y_train)

print("Model training completed")

Model training completed

In [14]:
y_pred = model.predict(X_test)

print("Predicted values:")
print(y_pred[:10])

Predicted values:
[0 1 0 1 0 0 1 0 0 0]

In [15]:
comparison = pd.DataFrame({
    "Actual": y_test.values,
    "Predicted": y_pred
})

comparison.head(10)

   Actual  Predicted
0       0          0
1       1          1
2       0          0
3       1          1
4       0          0
5       0          0
6       1          1
7       0          0
8       0          0
9       0          0

In [16]:
cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[61  2]
 [10 27]]

In [17]:
TN = cm[0][0]
FP = cm[0][1]
FN = cm[1][0]
TP = cm[1][1]

print("True Negative:", TN)
print("False Positive:", FP)
print("False Negative:", FN)
print("True Positive:", TP)

True Negative: 61
False Positive: 2
False Negative: 10
True Positive: 27

In [18]:
accuracy = (TP + TN) / (TP + TN + FP + FN)

print("Accuracy:", accuracy)

Accuracy: 0.88

In [19]:
error_rate = (FP + FN) / (TP + TN + FP + FN)

print("Error Rate:", error_rate)

Error Rate: 0.12

In [20]:
precision = TP / (TP + FP)

print("Precision:", precision)

Precision: 0.9310344827586207

In [21]:
recall = TP / (TP + FN)

print("Recall:", recall)

Recall: 0.7297297297297297

In [22]:
print("Model Performance Measures")
print("--------------------------")
print("True Positive:", TP)
print("False Positive:", FP)
print("True Negative:", TN)
print("False Negative:", FN)
print("Accuracy:", accuracy)
print("Error Rate:", error_rate)
print("Precision:", precision)
print("Recall:", recall)

Model Performance Measures
--------------------------
True Positive: 27
False Positive: 2
True Negative: 61
False Negative: 10
Accuracy: 0.88
Error Rate: 0.12
Precision: 0.9310344827586207
Recall: 0.7297297297297297