In [ ]:
"""

 pr3 Descriptive Statistics - Measures of Central Tendency and variability
Perform the following operations on any open source dataset (e.g., data.csv)
1. Provide summary statistics (mean, median, minimum, maximum, standard deviation) for
a dataset (age, income etc.) with numeric variables grouped by one of the qualitative
(categorical) variable. For example, if your categorical variable is age groups and
quantitative variable is income, then provide summary statistics of income grouped by the
age groups. Create a list that contains a numeric value for each response to the categorical
variable.
2. Write a Python program to display some basic statistical details like percentile, mean,
standard deviation etc. of the species of ‘Iris-setosa’, ‘Iris-versicolor’ and ‘Iris-versicolor’
of iris.csv dataset.
Provide the codes with outputs and explain everything that you do in this step.
"""

In [12]:
import pandas as pd
import numpy as np

In [14]:
df = pd.read_csv("Employee_Salary_Dataset.csv")

df.columns = df.columns.str.strip().str.lower()

print("Employee Salary dataset loaded successfully")
df.head()

Employee Salary dataset loaded successfully

   id  experience_years  age  gender  salary
0   1                 5   28  Female  250000
1   2                 1   21    Male   50000
2   3                 3   23  Female  170000
3   4                 2   22    Male   25000
4   5                 1   17    Male   10000

In [15]:
print("Dataset Information:")
df.info()

print("\nShape of Dataset:")
print(df.shape)

print("\nColumn Names:")
print(df.columns)

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                35 non-null     int64
 1   experience_years  35 non-null     int64
 2   age               35 non-null     int64
 3   gender            35 non-null     object
 4   salary            35 non-null     int64
dtypes: int64(4), object(1)
memory usage: 1.5+ KB

Shape of Dataset:
(35, 5)

Column Names:
Index(['id', 'experience_years', 'age', 'gender', 'salary'], dtype='object')

In [16]:
print("Missing values in each column:")
print(df.isnull().sum())

Missing values in each column:
id                  0
experience_years    0
age                 0
gender              0
salary              0
dtype: int64

In [17]:
numeric_columns = df.select_dtypes(include=[np.number]).columns

categorical_columns = df.select_dtypes(include=["object"]).columns

for col in numeric_columns:
    df[col] = df[col].fillna(df[col].median())

for col in categorical_columns:
    df[col] = df[col].fillna(df[col].mode()[0])

print("Missing values after handling:")
print(df.isnull().sum())

Missing values after handling:
id                  0
experience_years    0
age                 0
gender              0
salary              0
dtype: int64

In [18]:
group_column = "gender"

numeric_variables = ["age", "experience_years", "salary"]

print("Categorical variable used for grouping:", group_column)

print("\nNumeric variables used:")
print(numeric_variables)

Categorical variable used for grouping: gender

Numeric variables used:
['age', 'experience_years', 'salary']

In [19]:
summary_statistics = df.groupby(group_column)[numeric_variables].agg([
    "mean",
    "median",
    "min",
    "max",
    "std"
])

summary_statistics

              age                           experience_years                 \
             mean median min max        std             mean median min max
gender
Female  37.111111   31.0  21  62  15.449686        10.111111    7.5   1  27
Male    33.764706   29.0  17  62  13.997899         8.235294    6.0   1  25

                        salary
             std          mean    median   min       max           std
gender
Female  8.123234  2.054917e+06  250000.0  6000  10000000  3.450120e+06
Male    7.013642  2.063626e+06  220100.0  3000   7600000  2.950974e+06

In [20]:
salary_list_by_gender = df.groupby("gender")["salary"].apply(list)

print("List of salary values grouped by gender:")
print(salary_list_by_gender)

List of salary values grouped by gender:
gender
Female    [250000, 170000, 800000, 9000, 61500, 650000, ...
Male      [50000, 25000, 10000, 5001000, 1400000, 600005...
Name: salary, dtype: object

In [21]:
print("Basic Statistics of Salary:")

print("Mean:", df["salary"].mean())
print("Median:", df["salary"].median())
print("Minimum:", df["salary"].min())
print("Maximum:", df["salary"].max())
print("Standard Deviation:", df["salary"].std())

Basic Statistics of Salary:
Mean: 2059147.142857143
Median: 250000.0
Minimum: 3000
Maximum: 10000000
Standard Deviation: 3170123.635901818

In [23]:
iris = pd.read_csv("dsbdal.csv")

iris.columns = iris.columns.str.strip().str.lower()

print("Iris dataset loaded successfully")
iris.head()

Iris dataset loaded successfully

    id  sepallengthcm  sepalwidthcm  petallengthcm  petalwidthcm      species
0  1.0            5.1           3.5            1.4           0.2  Iris-setosa
1  2.0            4.9           3.0            1.4           0.2  Iris-setosa
2  3.0            4.7           3.2            1.3           0.2  Iris-setosa
3  4.0            4.6           3.1            1.5           0.2  Iris-setosa
4  5.0            5.0           3.6            1.4           0.2  Iris-setosa

In [24]:
print("Iris Dataset Information:")
iris.info()

print("\nShape of Iris Dataset:")
print(iris.shape)

print("\nColumn Names:")
print(iris.columns)

Iris Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 147 entries, 0 to 146
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             143 non-null    float64
 1   sepallengthcm  145 non-null    float64
 2   sepalwidthcm   146 non-null    float64
 3   petallengthcm  145 non-null    float64
 4   petalwidthcm   147 non-null    float64
 5   species        143 non-null    object
dtypes: float64(5), object(1)
memory usage: 7.0+ KB

Shape of Iris Dataset:
(147, 6)

Column Names:
Index(['id', 'sepallengthcm', 'sepalwidthcm', 'petallengthcm', 'petalwidthcm',
       'species'],
      dtype='object')

In [25]:
if "id" in iris.columns:
    iris = iris.drop("id", axis=1)

print("Dataset after removing ID column if present:")
iris.head()

Dataset after removing ID column if present:

   sepallengthcm  sepalwidthcm  petallengthcm  petalwidthcm      species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [26]:
print("Species values:")
print(iris["species"].unique())

Species values:
['Iris-setosa' nan 'Iris-versicolor' 'Iris-virginica']

In [27]:
iris_numeric_columns = iris.select_dtypes(include=[np.number]).columns

print("Numeric columns in Iris dataset:")
print(iris_numeric_columns)

Numeric columns in Iris dataset:
Index(['sepallengthcm', 'sepalwidthcm', 'petallengthcm', 'petalwidthcm'], dtype='object')

In [28]:
iris_setosa = iris[iris["species"] == "Iris-setosa"]

iris_versicolor = iris[iris["species"] == "Iris-versicolor"]

iris_virginica = iris[iris["species"] == "Iris-virginica"]

In [29]:
print("Statistical details of Iris-setosa:")

iris_setosa[iris_numeric_columns].describe()

Statistical details of Iris-setosa:

       sepallengthcm  sepalwidthcm  petallengthcm  petalwidthcm
count      45.000000     45.000000      43.000000     45.000000
mean        5.060000      3.444444       1.458140      0.240000
std         0.466807      0.351979       0.181571      0.109545
min         4.300000      2.900000       1.000000      0.100000
25%         4.800000      3.200000       1.400000      0.200000
50%         5.000000      3.400000       1.500000      0.200000
75%         5.300000      3.700000       1.500000      0.300000
max         7.000000      4.400000       1.900000      0.600000

In [30]:
print("Statistical details of Iris-versicolor:")

iris_versicolor[iris_numeric_columns].describe()

Statistical details of Iris-versicolor:

       sepallengthcm  sepalwidthcm  petallengthcm  petalwidthcm
count      49.000000     49.000000      49.000000      49.00000
mean        5.928571      2.769388       4.251020       1.32449
std         0.498748      0.319638       0.470426       0.19951
min         4.900000      2.000000       3.000000       1.00000
25%         5.600000      2.500000       4.000000       1.20000
50%         5.900000      2.800000       4.300000       1.30000
75%         6.300000      3.000000       4.600000       1.50000
max         6.900000      3.400000       5.100000       1.80000

In [31]:
print("Statistical details of Iris-virginica:")

iris_virginica[iris_numeric_columns].describe()

Statistical details of Iris-virginica:

       sepallengthcm  sepalwidthcm  petallengthcm  petalwidthcm
count      47.000000     48.000000      49.000000     49.000000
mean        6.589362      2.966667       5.557143      2.020408
std         0.653164      0.325729       0.556402      0.274605
min         4.900000      2.200000       4.500000      1.400000
25%         6.200000      2.800000       5.100000      1.800000
50%         6.500000      3.000000       5.600000      2.000000
75%         7.000000      3.125000       5.900000      2.300000
max         7.900000      3.800000       6.900000      2.500000

In [32]:
print("Group-wise statistical details of all species:")

iris.groupby("species")[iris_numeric_columns].describe()

Group-wise statistical details of all species:

                sepallengthcm                                               \
                        count      mean       std  min  25%  50%  75%  max
species
Iris-setosa              45.0  5.060000  0.466807  4.3  4.8  5.0  5.3  7.0
Iris-versicolor          49.0  5.928571  0.498748  4.9  5.6  5.9  6.3  6.9
Iris-virginica           47.0  6.589362  0.653164  4.9  6.2  6.5  7.0  7.9

                sepalwidthcm            ... petallengthcm      petalwidthcm  \
                       count      mean  ...           75%  max        count
species                                 ...
Iris-setosa             45.0  3.444444  ...           1.5  1.9         45.0
Iris-versicolor         49.0  2.769388  ...           4.6  5.1         49.0
Iris-virginica          48.0  2.966667  ...           5.9  6.9         49.0


                     mean       std  min  25%  50%  75%  max
species
Iris-setosa      0.240000  0.109545  0.1  0.2  0.2  0.3  0.6
Iris-versicolor  1.324490  0.199510  1.0  1.2  1.3  1.5  1.8
Iris-virginica   2.020408  0.274605  1.4  1.8  2.0  2.3  2.5

[3 rows x 32 columns]

In [33]:
print("Mean values grouped by species:")

iris.groupby("species")[iris_numeric_columns].mean()

Mean values grouped by species:

                 sepallengthcm  sepalwidthcm  petallengthcm  petalwidthcm
species
Iris-setosa           5.060000      3.444444       1.458140      0.240000
Iris-versicolor       5.928571      2.769388       4.251020      1.324490
Iris-virginica        6.589362      2.966667       5.557143      2.020408

In [34]:
print("Standard deviation grouped by species:")

iris.groupby("species")[iris_numeric_columns].std()

Standard deviation grouped by species:

                 sepallengthcm  sepalwidthcm  petallengthcm  petalwidthcm
species
Iris-setosa           0.466807      0.351979       0.181571      0.109545
Iris-versicolor       0.498748      0.319638       0.470426      0.199510
Iris-virginica        0.653164      0.325729       0.556402      0.274605