In [15]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler

In [16]:
df = pd.read_csv("dsbdal.csv")

df.columns = df.columns.str.strip()

print("Dataset loaded successfully")
df.head()

Dataset loaded successfully

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0  1.0            5.1           3.5            1.4           0.2  Iris-setosa
1  2.0            4.9           3.0            1.4           0.2  Iris-setosa
2  3.0            4.7           3.2            1.3           0.2  Iris-setosa
3  4.0            4.6           3.1            1.5           0.2  Iris-setosa
4  5.0            5.0           3.6            1.4           0.2  Iris-setosa

In [17]:
print("Dataset Description:")
print("This dataset is loaded from local device CSV file.")
print("It contains multiple variables/columns for data wrangling operations.")
print("Source: Local CSV file from device")

print("\nColumn Names:")
print(df.columns)

Dataset Description:
This dataset is loaded from local device CSV file.
It contains multiple variables/columns for data wrangling operations.
Source: Local CSV file from device

Column Names:
Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [18]:
print("Number of rows and columns:")
print(df.shape)

print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of rows and columns:
(147, 6)
Number of rows: 147
Number of columns: 6

In [19]:
print("Missing values in each column:")
print(df.isnull().sum())

Missing values in each column:
Id               4
SepalLengthCm    2
SepalWidthCm     1
PetalLengthCm    2
PetalWidthCm     0
Species          4
dtype: int64

In [20]:
print("Statistical summary of numeric columns:")
df.describe()

Statistical summary of numeric columns:

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  143.000000     145.000000    146.000000     145.000000    147.000000
mean    75.454545       5.859310      3.048630       3.835172      1.217687
std     43.362171       0.825336      0.436954       1.744775      0.758938
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     39.500000       5.100000      2.800000       1.600000      0.300000
50%     75.000000       5.800000      3.000000       4.400000      1.300000
75%    112.500000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [21]:
print("Description of all columns:")
df.describe(include="all")

Description of all columns:

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
count,143.000000,145.000000,146.000000,145.000000,147.000000,143
unique,NaN,NaN,NaN,NaN,NaN,3
top,NaN,NaN,NaN,NaN,NaN,Iris-versicolor
freq,NaN,NaN,NaN,NaN,NaN,49
mean,75.454545,5.859310,3.048630,3.835172,1.217687,NaN
std,43.362171,0.825336,0.436954,1.744775,0.758938,NaN
min,1.000000,4.300000,2.000000,1.000000,0.100000,NaN
25%,39.500000,5.100000,2.800000,1.600000,0.300000,NaN
50%,75.000000,5.800000,3.000000,4.400000,1.300000,NaN
75%,112.500000,6.400000,3.300000,5.100000,1.800000,NaN
max,150.000000,7.900000,4.400000,6.900000,2.500000,NaN

In [22]:
print("Data types of each column:")
print(df.dtypes)

Data types of each column:
Id               float64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

In [23]:
variable_description = pd.DataFrame({
    "Variable": df.columns,
    "Data Type": df.dtypes.values,
    "Missing Values": df.isnull().sum().values,
    "Unique Values": df.nunique().values
})

variable_description

        Variable Data Type  Missing Values  Unique Values
0             Id   float64               4            143
1  SepalLengthCm   float64               2             35
2   SepalWidthCm   float64               1             23
3  PetalLengthCm   float64               2             43
4   PetalWidthCm   float64               0             22
5        Species    object               4              3

In [24]:
numeric_columns = df.select_dtypes(include=[np.number]).columns

categorical_columns = df.select_dtypes(include=["object"]).columns

print("Numeric Columns:")
print(numeric_columns)

print("\nCategorical Columns:")
print(categorical_columns)

Numeric Columns:
Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm'], dtype='object')

Categorical Columns:
Index(['Species'], dtype='object')

In [25]:
for col in categorical_columns:
    df[col] = df[col].astype("category")

print("Data types after converting object columns to category:")
print(df.dtypes)

Data types after converting object columns to category:
Id                float64
SepalLengthCm     float64
SepalWidthCm      float64
PetalLengthCm     float64
PetalWidthCm      float64
Species          category
dtype: object

In [26]:
numeric_columns = df.select_dtypes(include=[np.number]).columns

scaler = MinMaxScaler()

df_normalized = df.copy()

df_normalized[numeric_columns] = scaler.fit_transform(df[numeric_columns])

print("Normalized data:")
df_normalized.head()

Normalized data:

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,0.000000,0.222222,0.625000,0.067797,0.041667,Iris-setosa
1,0.006711,0.166667,0.416667,0.067797,0.041667,Iris-setosa
2,0.013423,0.111111,0.500000,0.050847,0.041667,Iris-setosa
3,0.020134,0.083333,0.458333,0.084746,0.041667,Iris-setosa
4,0.026846,0.194444,0.666667,0.067797,0.041667,Iris-setosa

In [27]:
df_encoded = df.copy()

label_encoder = LabelEncoder()

for col in categorical_columns:
    df_encoded[col] = label_encoder.fit_transform(df_encoded[col].astype(str))

print("Dataset after Label Encoding:")
df_encoded.head()

Dataset after Label Encoding:

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0  1.0            5.1           3.5            1.4           0.2        0
1  2.0            4.9           3.0            1.4           0.2        0
2  3.0            4.7           3.2            1.3           0.2        0
3  4.0            4.6           3.1            1.5           0.2        0
4  5.0            5.0           3.6            1.4           0.2        0

In [28]:
df_one_hot = pd.get_dummies(df, columns=categorical_columns)

print("Dataset after One-Hot Encoding:")
df_one_hot.head()

Dataset after One-Hot Encoding:

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species_Iris-setosa,Species_Iris-versicolor,Species_Iris-virginica
0,1.0,5.1,3.5,1.4,0.2,True,False,False
1,2.0,4.9,3.0,1.4,0.2,True,False,False
2,3.0,4.7,3.2,1.3,0.2,True,False,False
3,4.0,4.6,3.1,1.5,0.2,True,False,False
4,5.0,5.0,3.6,1.4,0.2,True,False,False

In [29]:
print("Final Encoded Dataset Information:")
df_encoded.info()

print("\nFinal Dataset Shape:")
print(df_encoded.shape)

print("\nFinal Encoded Dataset:")
df_encoded.head()

Final Encoded Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 147 entries, 0 to 146
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             143 non-null    float64
 1   SepalLengthCm  145 non-null    float64
 2   SepalWidthCm   146 non-null    float64
 3   PetalLengthCm  145 non-null    float64
 4   PetalWidthCm   147 non-null    float64
 5   Species        147 non-null    int64
dtypes: float64(5), int64(1)
memory usage: 7.0 KB

Final Dataset Shape:
(147, 6)

Final Encoded Dataset:

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0  1.0            5.1           3.5            1.4           0.2        0
1  2.0            4.9           3.0            1.4           0.2        0
2  3.0            4.7           3.2            1.3           0.2        0
3  4.0            4.6           3.1            1.5           0.2        0
4  5.0            5.0           3.6            1.4           0.2        0